// x3core.idl : IDL source for x3core
//

// This file will be processed by the MIDL tool to
// produce the type library (x3core.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
    uuid(687E32A6-EDE4-453A-84BD-2C9436BB2071),
    version(1.0),
    helpstring("x3core 1.0 Type Library")
]
library X3Core
{
    importlib("stdole2.tlb");
};
